// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "app": {
      /**
       * Dismiss
       * @returns {Promise<void>} 
       */
      "Dismiss": () => {
        return window.go.main.app.Dismiss();
      },
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.go.main.app.Greet(arg1);
      },
      /**
       * Snooze
       * @returns {Promise<void>} 
       */
      "Snooze": () => {
        return window.go.main.app.Snooze();
      },
    },
  },

};
export default go;
