name: Go
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic .

      - name: Send coverage
        uses: codecov/codecov-action@v5
        with:
          files: coverage.txt
